// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: cards.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getCardsFomCollection = `-- name: GetCardsFomCollection :many
SELECT id, front, back, created_at, collection_id FROM cards WHERE collection_id=$1
`

func (q *Queries) GetCardsFomCollection(ctx context.Context, collectionID uuid.UUID) ([]Card, error) {
	rows, err := q.db.QueryContext(ctx, getCardsFomCollection, collectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Card
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.ID,
			&i.Front,
			&i.Back,
			&i.CreatedAt,
			&i.CollectionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
